update

diff --git a/gitrpush b/gitrpush
--- a/gitrpush
+++ b/gitrpush
@@ -74,7 +74,7 @@ for op in "$@";do
     esac
 done
 
-
+err_msg=
 
 if [ -z "$dom" ]; then
     echo "Domain (used with jssh) name must be given"
@@ -108,7 +108,8 @@ if $pull; then
     if git pull origin master; then
         echo 'Pulled from remote successfully'
     else
-        echo 'Failed to pull from remote'
+        echo 'E: Failed to pull from remote'
+        err_msg="${err_msg} E: Failed to pull from remote"
     fi
 fi
 
@@ -122,7 +123,8 @@ if git push $p_flags --all; then
     echo "Push to remote successful
 Re-attaching remote branch..."
 else
-    echo 'E: Failed to push to remote'; exit 1;
+    echo 'E: Failed to push to remote';
+    err_msg="${err_msg} E: Failed to push to remote"
 fi
 
 # reattach remote branch
@@ -133,14 +135,23 @@ if jssh "$dom" "cd '$wd'
     git checkout master &&
     echo 'Re-attached remote branch successfully'
     ## manage permission
-    find . -type f -name '*.php' -exec sh -c 'touch -r \"\$0\" .timestamp.nb; chmod 600 \"\$0\"; touch -r .timestamp.nb \"\$0\"; rm .timestamp.nb' {} \; &&
+    find . -type f -name '*.php' '!' -path '*/.git/*' -exec sh -c 'touch -r \"\$0\" .timestamp.nb; chmod 600 \"\$0\"; touch -r .timestamp.nb \"\$0\"; rm .timestamp.nb' {} \; &&
     echo 'Fixed php file permission'
+    find . -type f -name '*.sh' '!' -path '*/.git/*' -exec sh -c 'touch -r \"\$0\" .timestamp.nb; chmod 700 \"\$0\"; touch -r .timestamp.nb \"\$0\"; rm .timestamp.nb' {} \; &&
+    echo 'Fixed .sh file permission'
     find . -type d -exec sh -c 'touch -r \"\$0\" .timestamp.nb; chmod 755 \"\$0\"; touch -r .timestamp.nb \"\$0\"; rm .timestamp.nb' {} \; &&
     echo 'Fixed directory permission'
     "; then
     echo 'Successfully re-attached remote branch'
 else
-    echo "E: Failed to re-attach remote branch"; exit 1;
+    echo "E: Failed to re-attach remote branch";
+    err_msg="${err_msg} E: Failed to re-attach remote branch"
 fi
 
+if [ -n "$err_msg" ]; then
+	echo "$err_msg"
+	exit 1
+else
+    echo '***Success***'
+fi
 
