update

diff --git a/gitspush b/gitspush
--- a/gitspush
+++ b/gitspush
@@ -1,1 +1,72 @@
-../Git/Github/neurobin/jlutils/gitspush
+#!/bin/bash
+p_name=gitspush
+p_version=0.0.1
+ver_info="
+Name        : $p_name
+Version     : $p_version
+"
+help="
+########## gitspush #############
+git same push
+pushes same content to two or three brances
+branches are:
+    1. master
+    2. release
+    3. (user defined)
+
+Options:
+    -b : branch name
+    -m : comment
+"
+
+branch=""
+comment="update"
+for op in "$@";do
+    case "$op" in
+        -v|--version)
+            echo "$ver_info"
+            shift
+            exit 0
+            ;;
+        -h|--help)
+            echo "$help"
+            shift
+            exit 0
+            ;;
+        -b)
+            shift
+            branch="$1"
+            shift
+            ;;
+        -m)
+            shift
+            comment="$1"
+            shift
+            ;;
+        
+        -*)
+            echo "E: Invalid option: $1"
+            shift
+            exit 1
+            ;;
+    esac
+done
+
+if ! git branch |grep '^*'|grep '\bmaster$' > /dev/null 2>&1; then
+    echo "E: Not in the master branch"
+    exit 1
+fi
+
+{ git add --all :/ || git add --all; } &&
+git commit -m "$comment"
+{ git checkout release || git checkout -b release; } &&
+git merge -m "$comment" master
+if [[ $branch != "" ]];then 
+	git checkout "$branch" || git checkout -b "$branch"
+	git merge -m "$comment" master
+fi
+git checkout master
+git push --all &&
+echo Success
+
+
diff --git a/myavconv b/myavconv
--- a/myavconv
+++ b/myavconv
@@ -1,1 +1,76 @@
-../Git/Github/neurobin/jlutils/myavconv
+#!/bin/sh
+#set -x
+id='.'
+od='.'
+count=0
+globs=
+topt=$#
+overwrite=false
+while [ $# -gt 0 ]
+do
+    count=$(expr $count + 1)
+    case "$1" in
+        -id|--input-dir)
+            id="$2"
+            if [ ! -d "$id" ]; then
+                echo "E: No such directory: '$id'"
+                exit 1
+            fi
+            shift
+            ;;
+
+        -od|--output-dir)
+            od="$2"
+            mkdir -p "$od"
+            if [ ! -d "$od" ]; then
+                echo "E: No such directory: '$od'"
+                exit 1
+            fi
+            shift
+            ;;
+        -ox|--ouptput-extension)
+            oext=$2
+            shift
+            ;;
+        -ov|--overwrite)
+            overwrite=true
+            ;;
+        --help|-h)
+            echo "Usage:"
+            echo "  myavconv [options] input-extension/s"
+            echo "    -ox  \"output extension\""
+            echo "    -id  \"input directory\""
+            echo "    -od  \"output directory\""
+            echo "    -ov  \"overwrite\""
+            echo "    -h   \"help menu\""
+            exit 1
+            ;;
+        *)
+            if [ "$globs" = '' ]; then
+                globs="-name '*$1'"
+            else
+                globs="$globs -o -name '*$1'"
+            fi
+            ;;
+    esac
+    shift
+done
+oext=$(echo "$oext" |sed -n 's/^[.]*//p')
+if [ "$oext" = '' ]; then
+    echo 'E: output extension required'
+    exit 1
+fi
+
+find "$id" -type f $globs -exec $SHELL -c "
+fp=\$1
+od=\$2
+fpwe=\$(echo \"\$fp\" |sed -n 's/\(.*\)\.[^.]*$/\1/p')
+fpwe=\$(echo \"\$fpwe\" |sed -n 's#^[./]*##p')
+d=\$(dirname \"\$fpwe\")
+mkdir -p \"\$od/\$d\"
+if [[ ! -f \"\$od/\$fpwe.$oext\" ]] || $overwrite; then
+    avconv -i \"\$fp\" \"\$od/\$fpwe.$oext\"
+else
+    echo \"Skipping existing file: \$od/\$fpwe.$oext\"
+fi
+" "$0" '{}' "$od" \;
diff --git a/plymouth-preview b/plymouth-preview
--- a/plymouth-preview
+++ b/plymouth-preview
@@ -1,1 +1,35 @@
-../Git/Github/neurobin/jlutils/plymouth-preview
+#!/bin/sh
+
+#*** Preview Plymouth Splash ***#
+#*    Md Jahidul Hamid         *#
+#*    www.neurobin.org         *#
+#*    License: GPL v3          *#
+#*******************************#
+
+chkroot () {
+  if [ ! $(id -u) -eq 0 ]; then
+    echo "E: Must run as root"
+    exit 1
+  fi
+}
+
+chkroot
+
+duration="$1"
+if [ "$duration" = "" ]; then
+  duration=5
+else
+  if ! echo "$duration" |grep '^[0-9]*$'; then
+    echo "E: Invalid duration: $duration"
+    exit 1
+  fi
+fi
+
+plymouthd
+plymouth --show-splash
+for i in $(seq 0 $duration); do
+  plymouth --update=test$I
+  sleep 1
+done
+plymouth quit
+
