update

diff --git a/plymouth-preview b/plymouth-preview
--- a/plymouth-preview
+++ b/plymouth-preview
@@ -1,25 +1,26 @@
 #!/bin/sh
 
-## Preview Plymouth Splash       ##
-## by Md Jahidul Hamid           ##
-##    www.neurobin.org           ##
-##    License: GPL v3            ##
+#*** Preview Plymouth Splash ***#
+#*    Md Jahidul Hamid         *#
+#*    www.neurobin.org         *#
+#*    License: GPL v3          *#
+#*******************************#
 
-chk_root () {
-  if [ ! $( id -u ) -eq 0 ]; then
-    echo Must be run as root
-    exit
+chkroot () {
+  if [ ! $(id -u) -eq 0 ]; then
+    echo "E: Must run as root"
+    exit 1
   fi
 }
 
-chk_root
+chkroot
 
 duration="$1"
 if [ "$duration" = "" ]; then
   duration=5
 else
   if ! echo "$duration" |grep '^[0-9]*$'; then
-    echo "Invalid duration: $duration"
+    echo "E: Invalid duration: $duration"
     exit 1
   fi
 fi
